services:
  service:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${ANX_PATH}:/app/ANX
      - $HOME:/root:rw
    environment:
      API_TOKEN: ${API_TOKEN}
