services:
  service:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${ANX_PATH}:/app/ANX
    environment:
      API_TOKEN: ${API_TOKEN}
      GH_TOKEN: ${GH_TOKEN}
